class DataListModel {
  String id,
      IMAGE1,
      IMAGE2,
      logo,
      name,
      address,
      phone,
      gallary,
      tel,
      opening,
      lat,
      lng,
      city,
      cityId,
      mobile,
      fax,
      ARTIST_NAME_R,
      ARTIST_NAME_C,
      SKYPE,
      FACEBOOK,
      TWITTER,
      FLICKR,
      INSTAGRAM,
      YOUTUBE,
      VIMEO,
      LINKEDIN,
      PINTEREST,
      WORDPRESS,
      BLOGGER,
      TUMBLR,
      FOURSQUARE,
      ABSTRACT,
      XING,
      GOOGLEPLUS,
      WEIBO,
      GOOGLEMAP,
      BEHANCE,
      PRESS_RELEASE,
      link,
      EMAIL;

  DataListModel(
      this.id,
      this.IMAGE1,
      this.IMAGE2,
      this.logo,
      this.name,
      this.address,
      this.phone,
      this.gallary,
      this.tel,
      this.opening,
      this.lat,
      this.lng,
      this.city,
      this.cityId,
      this.mobile,
      this.fax,
      this.SKYPE,
      this.FACEBOOK,
      this.TWITTER,
      this.FLICKR,
      this.INSTAGRAM,
      this.YOUTUBE,
      this.VIMEO,
      this.LINKEDIN,
      this.PINTEREST,
      this.WORDPRESS,
      this.BLOGGER,
      this.TUMBLR,
      this.FOURSQUARE,
      this.ABSTRACT,
      this.XING,
      this.GOOGLEPLUS,
      this.WEIBO,
      this.GOOGLEMAP,
      this.BEHANCE,
      this.ARTIST_NAME_R,
      this.ARTIST_NAME_C,
      this.PRESS_RELEASE,
      this.link,
      this.EMAIL);

  /// Factory constructor for creating a new instance from a map
  factory DataListModel.fromJson(Map<String, dynamic> json) {
    return DataListModel(
      json['id'] ?? '',
      json['IMAGE1'] ?? '',
      json['IMAGE2'] ?? '',
      json['logo'] ?? '',
      json['name'] ?? '',
      json['address'] ?? '',
      json['phone'] ?? '',
      json['gallary'] ?? '',
      json['tel'] ?? '',
      json['opening'] ?? '',
      json['lat'] ?? '',
      json['lng'] ?? '',
      json['city'] ?? '',
      json['cityId'] ?? '',
      json['mobile'] ?? '',
      json['fax'] ?? '',
      json['SKYPE'] ?? '',
      json['FACEBOOK'] ?? '',
      json['TWITTER'] ?? '',
      json['FLICKR'] ?? '',
      json['INSTAGRAM'] ?? '',
      json['YOUTUBE'] ?? '',
      json['VIMEO'] ?? '',
      json['LINKEDIN'] ?? '',
      json['PINTEREST'] ?? '',
      json['WORDPRESS'] ?? '',
      json['BLOGGER'] ?? '',
      json['TUMBLR'] ?? '',
      json['FOURSQUARE'] ?? '',
      json['ABSTRACT'] ?? '',
      json['XING'] ?? '',
      json['GOOGLEPLUS'] ?? '',
      json['WEIBO'] ?? '',
      json['GOOGLEMAP'] ?? '',
      json['BEHANCE'] ?? '',
      json['ARTIST_NAME_R'] ?? '',
      json['ARTIST_NAME_C'] ?? '',
      json['PRESS_RELEASE'] ?? '',
      json['link'] ?? '',
      json['EMAIL'] ?? '',
    );
  }
}
