import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  // final List<Map<String,dynamic>> locale = [
  //   {'name': 'ENGLISH', 'locale': Locale('en', 'US')},
  //   {'name': 'Italian', 'locale': Locale('de', 'ITA')},
  //   {'name': 'Spanish', 'locale': Locale('de', 'SPA')},
  //   {'name': 'French', 'locale': Locale('de', 'FRA')},
  //   {'name': 'German', 'locale': Locale('de', 'GER')},
  //   {'name': 'Portuguese', 'locale': Locale('de', 'POR')},
  //   {'name': 'Chinese', 'locale': Locale('de', 'ZHO')},
  //   {'name': 'Russian', 'locale': Locale('de', 'RUS')},
  //   {'name': 'Japanese', 'locale': Locale('de', 'JPN')},
  // ];

  static final Map<String, Locale> locale = {
    'ENGLISH': Locale('en', 'US'),
    'Italian': Locale('de', 'ITA'),
    'Spanish': Locale('de', 'SPA'),
    'French': Locale('de', 'FRA'),
    'German': Locale('de', 'GER'),
    'Portuguese': Locale('de', 'POR'),
    'Chinese': Locale('de', 'ZHO'),
    'Russian': Locale('de', 'RUS'),
    'Japanese': Locale('de', 'JPN'),
  };

  static updateLanguage(Locale locale) async {
    // Get.back();
    await Get.updateLocale(locale);
  }

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'GALLERY': 'GALLERY',
          'MUSEUM': 'MUSEUM',
          'FAIRS': 'FAIRS',
          'ART CONSULTANTS': 'ART CONSULTANTS',
          'PRESS OFFICE': 'PRESS OFFICE',
          'Gallary': 'Gallary',
          'Museum': 'Museum',
          'Fairs': 'Fairs',
          'Art Consultants': 'Art Consultants',
          'Press Office': 'Press Office',
          'New': 'New',
          'Search': 'Search',
          'New Acquisition': 'New Acquisition',
          'City': 'City',
          'Select Language': 'Select Language',
          'filter': 'filter',
          'Details': 'Details',
          'Name': 'Name',
          'Country': 'Country',
          'Email': 'Email',
          'Website': 'Website',
          'Could not launch': 'Could not launch',
          'Artists': 'Artists',
          'No Data Found': 'No Data Found',
          'Places': 'Places',
          'Opening': 'Opening',
          'PORTFOLIO': 'PORTFOLIO',
          'here33': 'here33',
          'Address': 'Address',
          'Fax': 'Fax',
          'Home': 'Home',
          'Select Country': 'Select Country',
          'Select City': 'Select City',
          'Select Category': 'Select Category',
          'View Map': 'View Map',
          'View List': 'View List',
          'status': 'status',
          'Business Finder': 'Business Finder',
          'Map': 'Map',
          'Show more': 'Show more',
          'Counter increments smoke test': 'Counter increments smoke test',
          'Phone': 'Phone',
          'All Artists': 'All Artists'
        },
        'de_ITA': {
          'GALLERY': 'Gallerie',
          'MUSEUM': ' Musei',
          'FAIRS': 'Fiere',
          'ART CONSULTANTS': 'Consulenti d\'arte',
          'PRESS OFFICE': 'Ufficio Stampa',
          'Gallary': 'Gallerie',
          'Museum': ' Musei',
          'Fairs': 'Fiere',
          'Art Consultants': 'Consulenti d\'arte',
          'Press Office': 'Ufficio Stampa',
          'New': 'Nuovo',
          'Search': 'Ricerca',
          'New Acquisition': 'Nuova acquisizione',
          'Select Language': 'Seleziona la lingua',
          'filter': 'filtro',
          'Details': 'Dettagli',
          'Name': 'Nome',
          'City': 'Città',
          'Country': 'Paese',
          'Email': 'E-mail',
          'Website': 'Sito web',
          'Could not launch': 'Impossibile avviare',
          'Artists': 'Artisti',
          'No Data Found': 'Nessun dato trovato',
          'Places': 'posti',
          'Opening': 'Apertura',
          'PORTFOLIO': 'PORTAFOGLIO',
          'here33': 'qui33',
          'Address': 'Indirizzo',
          'Fax': 'Fax',
          'Home': 'Casa',
          'Select Country': 'Seleziona il paese',
          'Select City': 'Seleziona Città',
          'Select Category': 'Seleziona categoria',
          'View Map': 'Guarda la mappa',
          'View List': 'Visualizza elenco',
          'status': 'stato',
          'Business Finder': 'Trova affari',
          'Map': 'Carta geografica',
          'Show more': 'Mostra di più',
          'Counter increments smoke test': 'Il contatore incrementa il test del fumo',
          'Phone': 'Telefono',
          'All Artists': 'Tutti gli artisti'
        },
        'de_SPA': {
          'GALLERY': 'Galeria',
          'MUSEUM': 'Museo',
          'FAIRS': 'Ferias',
          'ART CONSULTANTS': 'Consultores de arte',
          'PRESS OFFICE': 'Oficina de prensa',
          'Gallary': 'Galeria',
          'Museum': 'Museo',
          'Fairs': 'Ferias',
          'Art Consultants': 'Consultores de arte',
          'Press Office': 'Oficina de prensa',
          'New': 'Nuevo',
          'Search': 'Búsqueda',
          'New Acquisition': 'Nueva adquisicion',
          'Select Language': 'Seleccione el idioma',
          'filter': 'filtrar',
          'Details': 'Detalles',
          'Name': 'Nombre',
          'City': 'Ciudad',
          'Country': 'País',
          'Email': 'Correo electrónico',
          'Website': 'Sitio web',
          'Could not launch': 'no se pudo iniciar',
          'Artists': 'Artistas',
          'No Data Found': 'Datos no encontrados',
          'Places': 'Lugares',
          'Opening': 'Apertura',
          'PORTFOLIO': 'PORTAFOLIO',
          'here33': 'aquí33',
          'Address': 'Habla a',
          'Fax': 'Fax',
          'Home': 'Casa',
          'Select Country': 'Seleccionar país',
          'Select City': 'Ciudad selecta',
          'Select Category': 'selecciona una categoría',
          'View Map': 'Ver el mapa',
          'View List': 'Ver lista',
          'status': 'estado',
          'Business Finder': 'Buscador de negocios',
          'Map': 'Mapa',
          'Show more': 'Mostrar más',
          'Counter increments smoke test': 'Prueba de humo de contador de incrementos',
          'Phone': 'Teléfono',
          'All Artists': 'Todas las artistas'
        },
        'de_FRA': {
          'GALLERY': 'Galerie',
          'MUSEUM': 'Musée',
          'FAIRS': 'Foires',
          'ART CONSULTANTS': 'Conseillers artistiques',
          'PRESS OFFICE': 'Bureau de presse',
          'Gallary': 'Galerie',
          'Museum': 'Musée',
          'Fairs': 'Foires',
          'Art Consultants': 'Conseillers artistiques',
          'Press Office': 'Bureau de presse',
          'New': 'Nouvelle',
          'Search': 'Rechercher',
          'New Acquisition': 'Nouvelle acquisition',
          'Select Language': 'Choisir la langue',
          'filter': 'filtre',
          'Details': 'Des détails',
          'Name': 'Nom',
          'City': 'Ville',
          'Country': 'De campagne',
          'Email': 'E-mail',
          'Website': 'Site Internet',
          'Could not launch': 'Impossible de lancer',
          'Artists': 'Artistes',
          'No Data Found': 'Aucune donnée disponible',
          'Places': 'Des endroits',
          'Opening': 'Ouverture',
          'PORTFOLIO': 'PORTEFEUILLE',
          'here33': 'ici33',
          'Address': 'Adresse',
          'Fax': 'Fax',
          'Home': 'Maison',
          'Select Country': 'Choisissez le pays',
          'Select City': 'Sélectionnez une ville',
          'Select Category': 'Choisir une catégorie',
          'View Map': 'Voir la carte',
          'View List': 'Afficher la liste',
          'status': 'statut',
          'Business Finder': 'Recherche d\'entreprise',
          'Map': 'Carte',
          'Show more': 'Montre plus',
          'Counter increments smoke test': 'Le compteur incrémente le test de fumée',
          'Phone': 'Téléphoner',
           'All Artists': 'Tous les artistes'
        },
        'de_GER': {
          'GALLERY': 'Galerie',
          'MUSEUM': 'Museum',
          'FAIRS': 'Messen',
          'ART CONSULTANTS': 'Kunstberater',
          'PRESS OFFICE': 'Pressebüro',
          'Gallary': 'Galerie',
          'Museum': 'Museum',
          'Fairs': 'Messen',
          'Art Consultants': 'Kunstberater',
          'Press Office': 'Pressebüro',
          'New': 'Neu',
          'Search': 'Suche',
          'New Acquisition': 'Neuanschaffung',
          'Select Language': 'Sprache auswählen',
          'filter': 'Filter',
          'Details': 'Einzelheiten',
          'Name': 'Name',
          'City': 'Stadt',
          'Country': 'Land',
          'Email': 'Email',
          'Website': 'Webseite',
          'Could not launch': 'Konnte nicht gestartet werden',
          'Artists': 'Künstler',
          'No Data Found': 'Keine Daten gefunden',
          'Places': 'Setzt',
          'Opening': 'Öffnung',
          'PORTFOLIO': 'PORTFOLIO',
          'here33': 'hier33',
          'Address': 'Adresse',
          'Fax': 'Fax',
          'Home': 'Zuhause',
          'Select Country': 'Land auswählen',
          'Select City': 'Stadt wählen',
          'Select Category': 'Kategorie wählen',
          'View Map': 'Ansichts Karte',
          'View List': 'Liste anzeigen',
          'status': 'Status',
          'Business Finder': 'Business-Finder',
          'Map': 'Karte',
          'Show more': 'Zeig mehr',
          'Counter increments smoke test': 'Der Zähler erhöht den Rauchtest',
          'Phone': 'Telefon',
          'All Artists': 'Alle Künstler'
        },
        'de_POR': {
          'GALLERY': 'Galeria',
          'MUSEUM': 'Museu',
          'FAIRS': 'Feiras',
          'ART CONSULTANTS': 'Consultores de arte',
          'PRESS OFFICE': 'Assessoria de Imprensa',
          'Gallary': 'Galeria',
          'Museum': 'Museu',
          'Fairs': 'Feiras',
          'Art Consultants': 'Consultores de arte',
          'Press Office': 'Assessoria de Imprensa',
          'New': 'Novo',
          'Search': 'Procurar',
          'New Acquisition': 'Nova aquisição',
          'Select Language': 'Selecione o idioma',
          'filter': 'filtro',
          'Details': 'Detalhes',
          'Name': 'Nome',
          'City': 'Cidade',
          'Country': 'País',
          'Email': 'E-mail',
          'Website': 'Local na rede Internet',
          'Could not launch': 'Não foi possível iniciar',
          'Artists': 'Abertura',
          'No Data Found': 'Nenhum dado encontrado',
          'Places': 'Lugares',
          'Opening': 'Abertura',
          'PORTFOLIO': 'CARTEIRA',
          'here33': 'aqui 33',
          'Address': 'Endereço',
          'Fax': 'Fax',
          'Home': 'Lar',
          'Select Country': 'Selecione o pais',
          'Select City': 'Selecione a cidade',
          'Select Category': 'Selecione a Categoria',
          'View Map': 'Ver mapa',
          'View List': 'Ver lista',
          'status': 'status',
          'Business Finder': 'Localizador de Negócios',
          'Map': 'Mapa',
          'Show more': 'Mostre mais',
          'Counter increments smoke test': 'O contador incrementa o teste de fumaça',
          'Phone': 'Telefone',
          'All Artists': 'Todos os artistas'
        },
        'de_ZHO': {
          'GALLERY': '画廊',
          'MUSEUM': '博物馆',
          'FAIRS': '展会',
          'ART CONSULTANTS': '艺术顾问',
          'PRESS OFFICE': '新闻办公室',
          'Gallary': '画廊',
          'Museum': '博物馆',
          'Fairs': '展会',
          'Art Consultants': '艺术顾问',
          'Press Office': '新闻办公室',
          'New': '新的',
          'Search': '搜索',
          'New Acquisition': '新收购',
          'Select Language': '选择语言',
          'filter': '筛选',
          'Details': '細節',
          'Name': '姓名',
          'City': '城市',
          'Country': '國家',
          'Email': '電子郵件',
          'Website': '網站',
          'Could not launch': '無法啟動',
          'Artists': '藝術家',
          'No Data Found': '沒有找到數據',
          'Places': '地方',
          'Opening': '開幕式',
          'PORTFOLIO': '文件夾',
          'here33': '這裡33',
          'Address': '地址',
          'Fax': '傳真',
          'Home': '家',
          'Select Country': '選擇國家',
          'Select City': '選擇城市',
          'Select Category': '選擇類別',
          'View Map': '查看地圖',
          'View List': '查看列表',
          'status': '狀態',
          'Business Finder': '業務查找器',
          'Map': '地圖',
          'Show more': '展示更多',
          'Counter increments smoke test': '計數器增加冒煙測試',
          'Phone': '電話',
          'All Artists': '所有艺术家'
        },
        'de_RUS': {
          'GALLERY': 'Галерея',
          'MUSEUM': 'музей',
          'FAIRS': 'Ярмарки',
          'ART CONSULTANTS': 'Консультанты по искусству',
          'PRESS OFFICE': 'Пресс-служба',
          'Gallary': 'Галерея',
          'Museum': 'музей',
          'Fairs': 'Ярмарки',
          'Art Consultants': 'Консультанты по искусству',
          'Press Office': 'Пресс-служба',
          'New': 'Новый',
          'Search': 'Поиск',
          'New Acquisition': 'Новое приобретение',
          'Select Language': 'Выбрать язык',
          'filter': 'фильтр',
          'Details': 'Подробности',
          'Name': 'Имя',
          'City': 'Город',
          'Country': 'Страна',
          'Email': 'Эл. адрес',
          'Website': 'Веб-сайт',
          'Could not launch': 'Не удалось запустить',
          'Artists': 'Художники',
          'No Data Found': 'Данные не найдены',
          'Places': 'Места',
          'Opening': 'Открытие',
          'PORTFOLIO': 'ПОРТФОЛИО',
          'here33': 'здесь33',
          'Address': 'Адрес',
          'Fax': 'Факс',
          'Home': 'Дома',
          'Select Country': 'Выберите страну',
          'Select City': 'Выберите город',
          'Select Category': 'выбрать категорию',
          'View Map': 'Посмотреть карту',
          'View List': 'Посмотреть список',
          'status': 'положение дел',
          'Business Finder': 'Поиск бизнеса',
          'Map': 'карта',
          'Show more': 'Показать больше',
          'Counter increments smoke test': 'Счетчик увеличивает дымовой тест',
          'Phone': 'Телефон',
          'All Artists': 'Все исполнители'
        },
        'de_JPN': {
          'GALLERY': 'ギャラリー',
          'MUSEUM': '美術館',
          'FAIRS': 'フェア',
          'ART CONSULTANTS': 'アートコンサルタント',
          'PRESS OFFICE': 'プレスオフィス',
          'Gallary': 'ギャラリー',
          'Museum': '美術館',
          'Fairs': 'フェア',
          'Art Consultants': 'アートコンサルタント',
          'Press Office': 'プレスオフィス',
          'New': '新しい',
          'Search': '検索',
          'New Acquisition': '新規買収',
          'Select Language': '言語を選択する',
          'filter': 'フィルター',
          'Details': '詳細',
          'Name': '名前',
          'City': '市',
          'Country': '国',
          'Email': 'Eメール',
          'Website': 'Webサイト',
          'Could not launch': '起動できませんでした',
          'Artists': 'アーティスト',
          'No Data Found': '何もデータが見つかりませんでした',
          'Places': '場所',
          'Opening': 'オープニング',
          'PORTFOLIO': 'ポートフォリオ',
          'here33': 'ここ33',
          'Address': '住所',
          'Fax': 'ファックス',
          'Home': '家',
          'Select Country': '国を選択',
          'Select City': '都市を選択',
          'Select Category': 'カテゴリを選んでください',
          'View Map': '地図を見ます',
          'View List': 'リストを見る',
          'status': 'スターテス',
          'Business Finder': 'ビジネスファインダー',
          'Map': '地図',
          'Show more': 'もっと見せる',
          'Counter increments smoke test': 'カウンター増分スモークテスト',
          'Phone': '電話',
          'All Artists': 'すべてのアーティスト'
        }
      };
}
